# Generated by Django 5.0.4 on 2024-04-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=10)),
                ('total_contents', models.IntegerField()),
                ('total_poems', models.IntegerField()),
                ('subject_teacher', models.CharField(max_length=20)),
                ('study_mode', models.CharField(choices=[('home', 'Home'), ('class', 'Class')], max_length=10)),
            ],
        ),
    ]
